apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        command:
        - /heapster
        - --source=kubernetes:''
        #- --source=kubernetes:http://10.211.55.23:8080
        - --sink=influxdb:http://monitoring-influxdb:8086
